-- this file is used to generate .t7 file for loading image name 
--
-------------------------------------------
-- trainPath is a table contains the name of the images in training set
-- trainGT is the table associate the name with its label, for example trainGT['3ac79f3df8dcd100755525327e8b4710b8122fdc.jpg'] = 1
-- likewise for testPath and testGT
-------------------------------------------
--
require 'gnuplot'
trainPath = {}
trainGT = {}

testPath = {}
testGT = {}

AllPath = {}
AllLabel = {}
sta = torch.Tensor(100):fill(0)
trainsta = torch.Tensor(100):fill(0)
teststa = torch.Tensor(100):fill(0)
for data in io.lines('/home/zxw/Baidu/datasets/train.txt') do            -- all the image name in training set provided, generated by 
	imagename, label = data:match("([^,]+) ([^,]+)")
	sta[label] = sta[label] + 1
	AllLabel[imagename] = label
	--print(imagename,
end
--print(AllLabel)
x = torch.range(1,100)--[[
gnuplot.pngfigure('allStatistic.png')
gnuplot.axis{1,100,0,''}
gnuplot.plot(x,sta)
gnuplot.close()
--]]

for data in io.lines('/home/zxw/Baidu/datasets/train/imagename.txt') do
	table.insert(AllPath,data)
end

local shuffle = torch.randperm(#AllPath)
--print(shuffle)
for i = 1, #AllPath do
	if i <= 2180 then                                       -- 80% of the images is used for training, 20% is uesd for validating.
		trainGT[AllPath[shuffle[i]]] = AllLabel[AllPath[shuffle[i]]]
		table.insert(trainPath,AllPath[shuffle[i]])
		trainsta[AllLabel[AllPath[shuffle[i]]]] = trainsta[AllLabel[AllPath[shuffle[i]]]] +1   -- count the number of
	else
		testGT[AllPath[shuffle[i]]] = AllLabel[AllPath[shuffle[i]]] 
		table.insert(testPath,AllPath[shuffle[i]])
		teststa[AllLabel[AllPath[shuffle[i]]]] = teststa[AllLabel[AllPath[shuffle[i]]]] +1
	end
	--print(AllLabel(i))
end --]]
gnuplot.pngfigure('trainStatistic.png')                         -- visualise the result and save as png image
gnuplot.axis{1,100,0,''}
gnuplot.plot(x,trainsta)
gnuplot.close()


gnuplot.pngfigure('testStatistic.png')
gnuplot.axis{1,100,0,''}
gnuplot.plot(x,teststa)
gnuplot.close()

torch.save('trainGT.t7',trainGT)
torch.save('testGT.t7',testGT)

torch.save('trainPath.t7',trainPath)
torch.save('testPath.t7',testPath)




